version: '3.7'
services:
  flask-app:
    build: ./flask-app
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
  database:
    build: ./db
    container_name: mysql
    ports:
    - target: 3306
      published: 3306
      protocol: tcp
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask-db
